// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Blog: typeof import('./components/Blog/index.vue')['default']
    Confetti: typeof import('./components/sweeper/Confetti.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Game: typeof import('./components/Game/index.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Heart: typeof import('./components/Heart/index.vue')['default']
    MineBlock: typeof import('./components/sweeper/MineBlock.vue')['default']
    Photo: typeof import('./components/Photo/index.vue')['default']
    Plum: typeof import('./components/Plum.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SunDark: typeof import('./components/SunDark.vue')['default']
    Sweeper: typeof import('./components/sweeper/index.vue')['default']
  }
}

export {}
